# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu14.04"

  config.vm.network "private_network", ip: "192.168.20.2"

  config.vm.hostname = "xke-demo"
  # config.vm.network "public_network"

  config.vm.synced_folder "./app", "/home/vagrant/app"


  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end


  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get -y update
    sudo apt-get install -y tomcat7
    rm -f /var/lib/tomcat7/webapps/ROOT/index.html
    cp -R /vagrant/app/*  /var/lib/tomcat7/webapps/ROOT

  SHELL
end
